import {createTypes} from 'reduxsauce';

export default createTypes(`
  YOUTUBE_CLEAR_SEARCH_RESULT
  YOUTUBE_PUT_SEARCH_RESULT
  YOUTUBE_PUT_RELATED_VIDEOS_RESULT
  YOUTUBE_CLEAR_RELATED_VIDEOS_RESULT
  YOUTUBE_PUT_API_KEY
`);
